name: CI Pipeline

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build Docker image
        run: |
          docker build \
            -f docker/Dockerfile \
            -t devops-platform-app:${{ github.sha }} \
            .